### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgame/FreeBoardGame.org#80]
```bash
jason@mithos-h ~/p/FreeBoardGame.org:master> yarn run dev                                                                                                                   
yarn run v1.13.0                                                                                                                                                            
$ run-s build webpack:watch                        
$ tsc                                                                                                                                                                       
$ webpack --watch --progress --config dev.webpack.config.js
 10% building 0/0 modules 0 active          
webpack is watching the files…                           
                                                  
(node:18357) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

![image](https://user-images.githubusercontent.com/304383/52185356-d02ebd80-27ec-11e9-972d-17a93c763ff0.png)

**Comment by jasonharrison** [comment]
I ran webpack with:
```node --trace-deprecation ./node_modules/.bin/webpack --watch --progress --config dev.webpack.config.js```

---

Seems to be a problem with **WebpackShellPlugin**.

```(node:10397) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at WebpackShellPlugin.apply (/home/jason/projects/FreeBoardGame.org/node_modules/webpack-shell-plugin/lib/index.js:236:16)
    at webpack (/home/jason/projects/FreeBoardGame.org/node_modules/webpack/lib/webpack.js:47:13)
    at processOptions (/home/jason/projects/FreeBoardGame.org/node_modules/webpack-cli/bin/cli.js:417:16)
    at yargs.parse (/home/jason/projects/FreeBoardGame.org/node_modules/webpack-cli/bin/cli.js:498:3)
    at Object.parse (/home/jason/projects/FreeBoardGame.org/node_modules/yargs/yargs.js:567:18)
    at /home/jason/projects/FreeBoardGame.org/node_modules/webpack-cli/bin/cli.js:210:8
    at Object.<anonymous> (/home/jason/projects/FreeBoardGame.org/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/jason/projects/FreeBoardGame.org/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)```
